# API endpoints

calculate_price:
  path: /calculate-price
  controller: App\Controller\ApiPaymentController::calculatePrice
  methods: POST

purchase:
  path: /purchase
  controller: App\Controller\ApiPaymentController::purchase
  methods: POST
  
###
